name: "CodeMaster"
description: "Universal Access Control & Lock/Keypad Synchronization Engine"
version: "1.1.0"
slug: "codemaster"
arch:
  - amd64
init: false
ingress: true
ingress_port: 8150
panel_icon: "mdi:lock-smart"
options:
  mqtt_host: "core-mosquitto"
  mqtt_port: 1883
schema:
  mqtt_host: "str"
  mqtt_port: "int"
image: "ghcr.io/spelech/codemaster"
